version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'renee-montoya-app'
    env_file:
      - .env
    volumes:
      - .:/application
    expose:
      - 5000
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  db_data: