version: "3"

services:


  nginx:
    build: ./docker/nginx/
    ports:
      - "1337:80"
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'renee-montoya-app'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - '5000:5000'
    command: ./wait-for-it.sh db:3306 -- gunicorn --bind localhost:5000 manage:app
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql


networks:
  app:
    driver: bridge

volumes:
  db_data: